import React from 'react';

const Terms = () => (
    <div className='terms'>
        <div className='terms__textcontent'>
            <h2>TERMS OF USE</h2>
            <p className='terms__paragraph'> The following document outlines the terms of use of the Colabi.co website. Before using any of the Colabi.co services, you are required to read, understand, and agree to these terms. Each section contains short explanation of the terms of use and is not legally binding.</p>
            <h4 className='terms__title'>DESCRIPTION OF SERVICE</h4>
            <p className='terms__paragraph'>Colabi.co (“Colabi.co”, “we”, “us” or “our”) provides a platform via its website, or any accompanied (the “Site”) to a community of registered users (“users” or “you”) to engage in a variety of activities, including to upload, download and share files of any type (“Files”, “Documents” or “Content”), create, edit and share tasks and schedules (“Content”), share and use messaging service for one-on-one communication (individually and collectively, the “Services”) with registered or unregistered members (individually and collectively, the ”Users”). The foregoing list of Services is not all-inclusive and additional Services may be offered by us from time to time. The following are the terms of use (“Terms”) for using the Site and the Services.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>We create this Site to be useful for creating and sharing basic features for better collaboration. We will also add and improve features in the future.</p>
            </div>
            <h4 className='terms__title'>ACCEPTANCE OF TERMS</h4>
            <p className='terms__paragraph'>BY USING THE SERVICES, YOU ARE AGREEING, ON BEHALF OF YOURSELF AND THOSE YOU REPRESENT, TO COMPLY WITH AND BE LEGALLY BOUND BY THESE TERMS AS WELL AS OUR PRIVACY POLICY AND ALL APPLICABLE LAWS. IF YOU, FOR YOURSELF OR ON BEHALF OF THOSE YOU REPRESENT, DO NOT AGREE TO ANY PROVISION OF THESE TERMS, YOU MUST, FOR YOURSELF AND ON BEHALF ANY SUCH PERSON(S), DISCONTINUE THE REGISTRATION PROCESS, DISCONTINUE YOUR USE OF THE SERVICES, AND, IF YOU ARE ALREADY REGISTERED, CANCEL YOUR ACCOUNT.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>By using Colabi.co, you agree to all the terms below.</p>
            </div>
            <h4 className='terms__title'>MODIFICATION OF TERMS</h4>
            <p className='terms__paragraph'>Colabi.co reserves the right, at its sole discretion, to modify or replace the Terms at any time. If the alterations constitute a material change to the Terms, Colabi.co will notify you by posting an announcement on the Site. What constitutes a material change will be determined at Colabi.co’s sole discretion. You are responsible for reviewing and becoming familiar with any such modifications. Using any Service or viewing any Content constitutes your acceptance of the Terms as modified.</p>            
            <p className='terms__paragraph'>In addition, when using particular features of the Services, you are subject to any posted guidelines, terms or rules applicable to such Services.</p>            
            <p className='terms__paragraph'>Your access to and use of the Site and our Services may be interrupted from time to time as a result of equipment malfunction, updating, maintenance or repair of the Site or any other reason within or outside of our control. Colabi.co reserves the right to suspend or discontinue the availability of the Site, any Service and to remove any Content at any time at its sole discretion and without prior notice. Colabi.co may also impose limits on certain features and Services or restrict your access to parts of or all of the Site and the Services without notice or liability. The Site should not be used or relied upon for storage of your Content and you are directed to retain your own copies of all Content posted on the Site.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>If these terms change, we will notify you. As well, at times things can go wrong and the service may be interrupted. It’s unlikely, but it can happen.</p>
            </div>
            <h4 className='terms__title'>REGISTRATION</h4>
            <p className='terms__paragraph'>As a condition to using Services, you are required to open an account with Colabi.co and select a password and username, and to provide registration information. The registration information you provide must be accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your access to the Services, by either terminating your email access or your account. Any personal information that you provide to Colabi.co is governed by the Colabi.co's <a href='/privacy'>Privacy Policy</a>.</p>   
            <p className='terms__paragraph'>You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you without appropriate authorization, or a name that is otherwise offensive, vulgar or obscene.</p>         
            <p className='terms__paragraph'>You are responsible for maintaining the confidentiality of your password and are solely responsible for all activities resulting from the use of your password and conducted through your Colabi.co account.</p>         
            <p className='terms__paragraph'>Services are available to authorized representatives of legal entities and to individuals who are at least 18 years old and who are authorized to access the Site by a parent or legal guardian. If you have authorized a minor to use the Site, you are responsible for the online conduct of such minor, and the consequences of any misuse of the Site by the minor. Parents and legal guardians are warned that the Site does open a means of communication to unknown entities that may be harmful to some.</p>         
            <p className='terms__paragraph'>To open an account with Colabi.co you are required to purchase a subscription and are bound to the terms under section Subscription.</p>         
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>To fully use the services, you need to create your own account, without violating other people’s rights. You also have to buy a subscription to use this service.</p>
            </div>
            <h4 className='terms__title'>SUBSCRIPTION</h4>
            <p className='terms__paragraph'>The following terms and conditions apply to subscription holders:</p>
            <ul>
                <li>Subscriptions are available on an annual and monthly membership basis.</li>
                <li>Subscriptions may modify, suspend or discontinue Services provided to Premium Account holders at any time at its sole discretion and without prior notice.</li>
                <li>We do not provide refunds on monthly subscription payments. Once you cancel your monthly payment, you’ll maintain access to your subscription until 30 days from payment has passed.</li>
                <li>Once your subscription has expired, you will no longer be able to use your account until new subscription is acquired.</li>
                <li>Any refund owing to you will be paid within 30 days of the Termination Date provided your written notice of termination includes your username and full name as it appears on your account or on your credit card.</li>   
            </ul> 
            <h4 className='terms__title'>FAIR STORAGE POLICY</h4>
            <p className='terms__paragraph'>Colabi.co maintains a fair storage policy to ensure stable and fast service to all users. The storage limits set forth in the Terms may be changed from time to time without notice and you are responsible for complying with such changes.</p>
            <p className='terms__paragraph'>All accounts are limited to a maximum of 10 task collections each then limited to 100 tasks.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>We limit amount of content each user can post. We may change those limits without any prior notice.</p>
            </div>
            <h4 className='terms__title'>USER CONDUCT</h4>
            <p className='terms__paragraph'>All Content posted or otherwise submitted to the Site, or other communications (“Communications”, with Content and Communications collectively referred to as “Content”) is the sole responsibility of the account holder from which such Communications originate and you acknowledge and agree that you, and not Colabi.co, are entirely responsible for all Content that you post, or otherwise submit to the Site, including via messages exchanged through Colabi.co’s messenger service. Colabi.co does not control user submitted Content and, as such, does not guarantee the accuracy, integrity or quality of such Content. You understand that by using the Site you may be exposed to Content that is offensive, indecent or objectionable.</p>
            <p className='terms__paragraph'>As a condition of use, you promise not to use the Services for any purpose that is unlawful or prohibited by these Terms, or any other purpose not reasonably intended by Colabi.co. By way of example, and not as a limitation, you agree not to use the Services:</p>
            <ul>
                <li>To abuse, harass, threaten, impersonate or intimidate any person;</li>
                <li>To post or transmit, or cause to be posted or transmitted, any Content that is libelous, defamatory, obscene, pornographic, abusive, offensive, profane, or that infringes any copyright or other right of any person;</li>
                <li>To communicate with Colabi.co representatives or other users in an abusive or offensive manner;</li>
                <li>For any purpose (including posting or viewing Content) that is not permitted under the laws of the jurisdiction where you use the Services;</li>
                <li>To post or transmit, or cause to be posted or transmitted, any Communication designed or intended to obtain password, account, or private information from any Colabi.co user;</li>
                <li>To create or transmit unwanted ‘spam’ to any person or any URL;</li>
                <li>You agree not to use any robot, spider, scraper or other automated means to access the Site for any purpose without our express written permission. Additionally, you agree that you will not: (i) take any action that imposes, or may impose in our sole discretion an unreasonable or disproportionately large load on our infrastructure; (ii) interfere or attempt to interfere with the proper working of the Site or any activities conducted on the Site; or (iii) bypass any measures we may use to prevent or restrict access to the Site;</li>
                <li>To sell, assign or otherwise transfer your profile.</li>
            </ul>
            <p className='terms__paragraph'>You are solely responsible for your interactions with other users of the Site, including any communications that you exchange through Colabi.co’s messenger service. Colabi.co reserves the right, but has no obligation, to review disputes between you and other users. This includes the right to review messages exchanged through Colabi.co messenger service, based on any reports that Colabi.co receives alleging the violation of these Terms through the use of Colabi.co's messenger service, including without limitation, reports regarding alleged harassment, indecency, and offensive messages.</p>
            <p className='terms__paragraph'>If the Services or Site are used in a manner that violates the Terms in any way, Colabi.co may at its sole discretion, but is not required to, suspend or terminate your account, disable your access to the Site and/or take any steps that it deems appropriate to address the situation.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>You cannot use our site to post or share illegal or pornographic material, harass people, send spam, and do other crazy stuff.</p>
            </div>
            <h4 className='terms__title'>LINKS</h4>
            <p className='terms__paragraph'>The Services may provide, or third parties may provide, links to other sites or resources. Because Colabi.co has no control over such sites and resources, you acknowledge and agree that Colabi.co is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that Colabi.co shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>Some people may post links; we are not responsible for those links.</p>
            </div>
            <h4 className='terms__title'>RELEASE AND INDEMNITY</h4>
            <p className='terms__paragraph'>You hereby expressly and irrevocably release and forever discharge Colabi.co, its affiliated and associated companies and its authorized distributors, and their respective directors, officers, employees, agents, representatives, independent and dependent contractors, licensees, successors and assigns of and from any and all actions, causes of action, suits, proceedings, liability, debts, judgments, claims and demands whatsoever in law or equity which you ever had, now have, or hereafter can, shall or may have, for or by reason of, or arising directly or indirectly out of your use of the Site and the Services.</p>
            <p className='terms__paragraph'>You hereby agree to indemnify and hold harmless Colabi.co, its affiliated and associated companies and its authorized distributors, and their respective directors, officers, employees, agents, representatives, independent and dependent contractors, licensees, successors and assigns from and against all claims, losses, expenses, damages and costs (including, but not limited to, direct, incidental, consequential, exemplary and indirect damages), and reasonable attorneys' fees, resulting from or arising out of (i) a breach of these Terms, (ii) Content posted on the Site, (iii) the use of the Services or Premium Accounts, by you or any person using your account or Colabi.co Username and password, (iv) the licensing or use of your Content, or (v) any violation of any rights of a third party. Colabi.co reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>We are not liable if something goes really wrong. Always have a backup of your stuff.</p>
            </div>
            <h4 className='terms__title'>TERMINATION</h4>
            <p className='terms__paragraph'>Colabi.co may terminate or suspend any and all Services and/or your Colabi.co account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination of your account, your right to use the Services will immediately cease. If you wish to terminate your Colabi.co account, you may simply discontinue using the Services (subject to termination provisions specific to Premium Accounts). All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership and rights provisions and warranties, warranty disclaimers, indemnity and limitations of liability.</p>
            <p className='terms__paragraph'>It is your responsibility to remove all Content from your account prior to termination. Upon termination of your account, Colabi.co will automatically remove all Content posted to your account.</p>
            <div className='terms__textbox'>
                <p className='terms__textbox__title'> IN SHORT: </p>
                <p className='terms__textbox__text'>We may stop providing services at any time. You can also stop using your account or close your account at any time.</p>
            </div>
            <h4 className='terms__title'>WARRANTY DISCLAIMER</h4>
            <p className='terms__paragraph'>YOU USE THE SITE AND THE SERVICES AT YOUR OWN RISK. THE SITE AND THE SERVICES ARE PROVIDED ON AN “AS IS, AS AVAILABLE” BASIS. Colabi.co EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING THE WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. Colabi.co DISCLAIMS ALL RESPONSIBILITY FOR ANY LOSS, INJURY, CLAIM, LIABILITY, OR DAMAGE OF ANY KIND RESULTING FROM, ARISING OUT OF OR IN ANY WAY RELATED TO (A) ANY ERRORS IN OR OMISSIONS FROM THIS SITE AND THE SERVICES, INCLUDING, BUT NOT LIMITED TO, TECHNICAL INACCURACIES AND TYPOGRAPHICAL ERRORS, (B) THIRD PARTY COMMUNICATIONS, (C) ANY THIRD PARTY WEBSITES OR CONTENT DIRECTLY OR INDIRECTLY ACCESSED THROUGH LINKS IN THE SITE, INCLUDING BUT NOT LIMITED TO ANY ERRORS OR OMISSIONS, (D) THE UNAVAILABILITY OF ALL OR ANY PART OF THE SITE OR THE SERVICES, (E) YOUR USE OF THE SITE OR THE SERVICES, OR (F) YOUR USE OF ANY EQUIPMENT OR SOFTWARE IN CONNECTION WITH THE SITE OR THE SERVICES.</p>
            <h4 className='terms__title'>LIMITATION OF LIABILITY</h4>
            <p className='terms__paragraph'>EXCEPT AS OTHERWISE PROVIDED BY LAW, NEITHER Colabi.co NOR ANY OF ITS AFFILIATES, PARENTS, SUBSIDIARIES, AUTHORIZED DISTRIBUTORS, DIRECTORS, SHAREHOLDERS, EMPLOYEES OR AGENTS SHALL BE LIABLE FOR ANY LOSS, INJURY, CLAIM, LIABILITY, OR DAMAGE OF ANY KIND RESULTING FROM YOUR USE OF THE SITE, ANY FACTS OR OPINIONS APPEARING THEREON, OR THE SERVICES. Colabi.co SHALL NOT BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER (INCLUDING, WITHOUT LIMITATION, ATTORNEYS’ FEES) IN ANY WAY DUE TO, RESULTING FROM, OR ARISING IN CONNECTION WITH THE USE OF OR INABILITY TO USE THE SITE OR SERVICES. TO THE EXTENT THE FOREGOING LIMITATION OF LIABILITY IS PROHIBITED OR FAILS OF ITS ESSENTIAL PURPOSE, Colabi.co's SOLE OBLIGATION TO YOU FOR DAMAGES SHALL BE LIMITED TO US$100.00. YOU AND Colabi.co AGREE THAT ANY PROCEEDINGS TO RESOLVE OR LITIGATE ANY DISPUTE ARISING HEREUNDER WILL BE CONDUCTED SOLELY ON AN INDIVIDUAL BASIS, AND THAT YOU WILL NOT SEEK TO HAVE ANY DISPUTE HEARD AS A CLASS ACTION, A REPRESENTATIVE ACTION, A COLLECTIVE ACTION, A PRIVATE ATTORNEY-GENERAL ACTION, OR IN ANY PROCEEDING IN WHICH YOU ACT OR PROPOSE TO ACT IN A REPRESENTATIVE CAPACITY. YOU FURTHER AGREE THAT NO PROCEEDING WILL BE JOINED, CONSOLIDATED, OR COMBINED WITH ANOTHER PROCEEDING WITHOUT THE PRIOR WRITTEN CONSENT OF Colabi.co AND ALL PARTIES TO ANY SUCH PROCEEDING.</p>
            <h4 className='terms__title'>MISCELLANEOUS</h4>
            <p className='terms__paragraph'>The Terms shall be governed by and construed in accordance with the laws of the Goverment of Austria, as applicable without regard to conflicts of laws principles. The United Nations Convention on the International Sale of Goods does not apply and is expressly excluded.</p>
            <p className='terms__paragraph'>Any controversies or disputes arising out of or relating to these Terms shall be resolved by binding arbitration in accordance with the then current Commercial Arbitration Rules of the American Arbitration Association or of the International Center for Dispute Resolution to be held in Wien, Austria. The parties shall select a mutually acceptable arbitrator knowledgeable about issues relating to the subject matter of these Terms. The arbitration proceeding shall be conducted in English and all documentation shall be presented and filed in English. The arbitrator shall not have the authority to modify any provision of these Terms or to award punitive damages. The arbitrator shall have the power to issue mandatory orders and restraint orders in connection with the arbitration. The decision rendered by the arbitrator shall be final and binding on the parties, and judgment may be entered in conformity with the decision in any court having jurisdiction. The prevailing party shall be entitled to recover its reasonable legal costs relating to that aspect of its claim or defense on which it prevails, and any opposing costs awards shall be offset. The agreement to arbitration shall be specifically enforceable under the prevailing arbitration law. During the continuance of any arbitration proceeding, the parties shall continue to perform their respective obligations under these Terms. The parties agree that, notwithstanding any otherwise applicable statute(s) of limitation, any arbitration proceeding shall be commenced within two years of the acts, events, or occurrences giving rise to the claim.</p>
            <p className='terms__paragraph'>You, agree to defend, indemnify and hold Colabi.co, its affiliates and its sponsors, partners, other co-branders and the respective directors, officers and employees of each harmless from and against any and all claims, losses, damages, liabilities and costs (including, without limitation, reasonable attorneys' fees and court costs) arising out of or relating to your breach of any of these Terms or use by you or any third party of the Services. Colabi.co reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you.</p>
            <p className='terms__paragraph'>These Terms constitute the entire understanding of the parties and supersede all prior and contemporaneous written and oral agreements with respect to the subject matter hereof. Any rule of construction stating that ambiguities are to be resolved against the drafting party will not be applied in the construction or interpretation of these Terms. If one or more of the provisions herein is held invalid, illegal or unenforceable in any respect, the validity, legality and enforcement of the remaining provisions shall not be affected or impaired. Any inconsistency between these Terms in English and these Terms in any other language shall, to the fullest extent permitted by applicable law, be resolved by reference to the English version. The failure to enforce or the waiver by either party of a default or breach of the other party shall not be considered to be a waiver of any prior, subsequent or other default or breach.</p>
            <h4 className='terms__title'>CHANGE LOG (NEWEST FIRST):</h4>
            <ul>
                <li><span>July 2018:</span> Wrote intial version of this document.</li>
            </ul>
        </div>    
    </div>
);

export default Terms;